version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  run_tests:
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
      - run:
          name: Install project dependencies
          command: npm install

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_tests
      - build_and_push:
          requires:
            - run_tests
          filters:
            branches:
              only: main
